"""Extension system for pilot.

Provides runtime loading of Python extension modules that can:
- Register LLM-callable tools
- Subscribe to agent lifecycle events
- Register slash commands and CLI flags
- Interact with the user via UI primitives
"""

from pilot.extensions.event_bus import EventBus, EventBusController, create_event_bus
from pilot.extensions.loader import (
    discover_and_load_extensions,
    discover_extensions_in_dir,
    load_extensions,
)
from pilot.extensions.runner import (
    ExtensionRunner,
    emit_project_trust_event,
    emit_session_shutdown_event,
)
from pilot.extensions.types import (
    AgentEndEvent,
    AgentStartEvent,
    AfterProviderResponseEvent,
    BeforeAgentStartEvent,
    BeforeAgentStartEventResult,
    BeforeProviderRequestEvent,
    CompactOptions,
    ContextEvent,
    ContextEventResult,
    ContextUsage,
    Extension,
    ExtensionAPI,
    ExtensionCommandContext,
    ExtensionContext,
    ExtensionContextActions,
    ExtensionEvent,
    ExtensionFactory,
    ExtensionFlag,
    ExtensionHandler,
    ExtensionMode,
    ExtensionRuntime,
    ExtensionUIContext,
    InputEvent,
    InputEventResult,
    InputSource,
    LoadExtensionsResult,
    MessageEndEvent,
    MessageEndEventResult,
    MessageStartEvent,
    MessageUpdateEvent,
    ModelSelectEvent,
    ProjectTrustContext,
    ProjectTrustEvent,
    ProjectTrustEventResult,
    RegisteredCommand,
    RegisteredTool,
    ResolvedCommand,
    ResourcesDiscoverEvent,
    ResourcesDiscoverResult,
    SessionBeforeCompactEvent,
    SessionBeforeCompactResult,
    SessionBeforeForkEvent,
    SessionBeforeForkResult,
    SessionBeforeSwitchEvent,
    SessionBeforeSwitchResult,
    SessionBeforeTreeEvent,
    SessionBeforeTreeResult,
    SessionCompactEvent,
    SessionEvent,
    SessionShutdownEvent,
    SessionStartEvent,
    SessionTreeEvent,
    SourceInfo,
    ThinkingLevelSelectEvent,
    ToolCallEvent,
    ToolCallEventResult,
    ToolDefinition,
    ToolExecutionEndEvent,
    ToolExecutionMode,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    ToolResultEvent,
    ToolResultEventResult,
    TreePreparation,
    TurnEndEvent,
    TurnStartEvent,
)
from pilot.extensions.wrapper import wrap_registered_tool, wrap_registered_tools
from pilot.extensions.agent_integration import (
    create_extension_before_tool_call,
    create_extension_after_tool_call,
    wire_extension_runner_to_config,
    emit_agent_start,
    emit_agent_end,
    emit_turn_start,
    emit_turn_end,
    emit_context_event,
)
from pilot.extensions.session_integration import (
    emit_session_start,
    emit_session_before_switch,
    emit_session_before_fork,
    emit_session_shutdown,
    emit_session_compact,
    emit_session_tree,
    handle_session_switch,
)

__all__ = [
    # Event bus
    "EventBus",
    "EventBusController",
    "create_event_bus",
    # Loader
    "discover_and_load_extensions",
    "discover_extensions_in_dir",
    "load_extensions",
    # Runner
    "ExtensionRunner",
    "emit_project_trust_event",
    "emit_session_shutdown_event",
    # Wrapper
    "wrap_registered_tool",
    "wrap_registered_tools",
    # Agent integration
    "create_extension_before_tool_call",
    "create_extension_after_tool_call",
    "wire_extension_runner_to_config",
    "emit_agent_start",
    "emit_agent_end",
    "emit_turn_start",
    "emit_turn_end",
    "emit_context_event",
    # Session integration
    "emit_session_start",
    "emit_session_before_switch",
    "emit_session_before_fork",
    "emit_session_shutdown",
    "emit_session_compact",
    "emit_session_tree",
    "handle_session_switch",
    # Core types
    "Extension",
    "ExtensionAPI",
    "ExtensionCommandContext",
    "ExtensionContext",
    "ExtensionContextActions",
    "ExtensionEvent",
    "ExtensionFactory",
    "ExtensionFlag",
    "ExtensionHandler",
    "ExtensionMode",
    "ExtensionRuntime",
    "ExtensionUIContext",
    "LoadExtensionsResult",
    "RegisteredCommand",
    "RegisteredTool",
    "ResolvedCommand",
    "SourceInfo",
    "ToolDefinition",
    "ToolExecutionMode",
    # Event types
    "AgentEndEvent",
    "AgentStartEvent",
    "AfterProviderResponseEvent",
    "BeforeAgentStartEvent",
    "BeforeAgentStartEventResult",
    "BeforeProviderRequestEvent",
    "ContextEvent",
    "ContextEventResult",
    "InputEvent",
    "InputEventResult",
    "InputSource",
    "MessageEndEvent",
    "MessageEndEventResult",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "ModelSelectEvent",
    "SessionBeforeCompactEvent",
    "SessionBeforeCompactResult",
    "SessionBeforeForkEvent",
    "SessionBeforeForkResult",
    "SessionBeforeSwitchEvent",
    "SessionBeforeSwitchResult",
    "SessionBeforeTreeEvent",
    "SessionBeforeTreeResult",
    "SessionCompactEvent",
    "SessionEvent",
    "SessionShutdownEvent",
    "SessionStartEvent",
    "SessionTreeEvent",
    "ThinkingLevelSelectEvent",
    "ToolCallEvent",
    "ToolCallEventResult",
    "ToolExecutionEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "ToolResultEvent",
    "ToolResultEventResult",
    "TreePreparation",
    "TurnEndEvent",
    "TurnStartEvent",
    # Result types
    "CompactOptions",
    "ContextUsage",
    "ProjectTrustContext",
    "ProjectTrustEvent",
    "ProjectTrustEventResult",
    "ResourcesDiscoverEvent",
    "ResourcesDiscoverResult",
]
